ARG NODE_VERSION=18.12.1
FROM node:${NODE_VERSION}-alpine3.17 AS uibuilder
WORKDIR /webui/
RUN npm config set update-notifier false

### Copy actual frontend source code
COPY webui .

### Compile frontend
RUN npm run build-prod


### Create final image
FROM ${DOCKER_PREFIX}nginx:1.23.3-alpine-slim

# Copy built frontend
COPY --from=uibuilder /webui/dist/ /usr/share/nginx/html/
